# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab4dbfc34c31007ff2ca875d95d931138c0af1b5d8b9749924153470f741a0d8bf3ff0f380e724e3a50b693de50e5197a5c0ec15f18add9b2c3258966f9f1952
  facebook_app_id: 195499437469828
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
test:
  secret_key_base: c02864e6055ee28f7f6c9891bc619f6b3abdffed508536773965a993c7f91d6111c5f6dd381a8b2309a91ccaef2c83a9867648e916d84176e49bd5af70efeb8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
